name: phpcs

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, zip, xml
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run test suite
        run: vendor/bin/phpcs src/ tests/
